/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

// Here you can find all details related to export declaration
type SupermodelIoLogisticsExpressExportDeclaration struct {
	// Please enter details for each export line item
	LineItems []SupermodelIoLogisticsExpressExportDeclarationLineItems `json:"lineItems"`
	Invoice   *SupermodelIoLogisticsExpressExportDeclarationInvoice    `json:"invoice"`
	// Please enter up to three remarks
	Remarks []SupermodelIoLogisticsExpressExportDeclarationRemarks `json:"remarks,omitempty"`
	// Please enter additional charge to appear on the invoice<BR>      admin, Administration Charge<BR>      delivery, Delivery Charge<BR>      documentation, Documentation Charge<BR>      expedite, Expedite Charge<BR>      freight, Freight Charge<BR>      fuel surcharge, Fuel Surcharge<BR>      logistic, Logistic Charge<BR>      other, Other Charge<BR>      packaging, Packaging Charge<BR>      pickup, Pickup Charge<BR>      handling, Handling Charge<BR>      vat, VAT Charge<BR>      insurance, Insurance Cost
	AdditionalCharges []SupermodelIoLogisticsExpressExportDeclarationAdditionalCharges `json:"additionalCharges,omitempty"`
	// Name of port of departure, shipment or destination as required under the applicable delivery term.
	PlaceOfIncoterm string `json:"placeOfIncoterm,omitempty"`
	// Please enter recipient reference
	RecipientReference string                                                                             `json:"recipientReference,omitempty"`
	Exporter           *SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationExporter `json:"exporter,omitempty"`
	// Please provide the reason for export
	ExportReasonType string `json:"exportReasonType,omitempty"`
	// Please provide the shipment was sent for Personal (Gift) or Commercial (Sale) reasons
	ShipmentType string `json:"shipmentType,omitempty"`
	// Please provide the Customs Documents at invoice level
	CustomsDocuments []SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationCustomsDocuments1 `json:"customsDocuments,omitempty"`
	// The Incoterms rules are a globally-recognized set of standards, used worldwide in international and domestic contracts for the delivery of goods, illustrating responsibilities between buyer and seller for costs and risk, as well as cargo insurance.<BR>      EXW ExWorks<BR>      FCA Free Carrier<BR>      CPT Carriage Paid To<BR>      CIP Carriage and Insurance Paid To<BR>      DPU Delivered at Place Unloaded<BR>      DAP Delivered at Place<BR>      DDP Delivered Duty Paid<BR>      FAS Free Alongside Ship<BR>      FOB Free on Board<BR>      CFR Cost and Freight<BR>      CIF Cost, Insurance and Freight<BR>      DAF Delivered at Frontier<BR>      DAT Delivered at Terminal<BR>      DDU Delivered Duty Unpaid<BR>      DEQ Delivery ex Quay<BR>      DES Delivered ex Ship
	Incoterm string `json:"incoterm"`
}
