/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

type SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetails struct {
	// This array contains all the DHL Express special handling feature codes
	ServiceHandlingFeatureCodes []string `json:"serviceHandlingFeatureCodes,omitempty"`
	// Here you can find calculated volumetric weight based on dimensions provided in the request
	VolumetricWeight float64 `json:"volumetricWeight,omitempty"`
	// Here you can find billing code which was applied on your shipment
	BillingCode string `json:"billingCode,omitempty"`
	// Here you can find the DHL Express shipment content code of your shipment
	ServiceContentCode     string                                                                    `json:"serviceContentCode,omitempty"`
	CustomerDetails        *SupermodelIoLogisticsExpressCreateShipmentResponseCustomerDetails        `json:"customerDetails,omitempty"`
	OriginServiceArea      *SupermodelIoLogisticsExpressCreateShipmentResponseOriginServiceArea      `json:"originServiceArea,omitempty"`
	DestinationServiceArea *SupermodelIoLogisticsExpressCreateShipmentResponseDestinationServiceArea `json:"destinationServiceArea,omitempty"`
	// Here you can find DHL Routing Code which was applied on your shipment
	DhlRoutingCode string `json:"dhlRoutingCode,omitempty"`
	// Here you can find DHL Routing Data ID which was applied on your shipment
	DhlRoutingDataId string `json:"dhlRoutingDataId,omitempty"`
	// Here you can find Delivery Date Code which was applied on your shipment
	DeliveryDateCode string `json:"deliveryDateCode,omitempty"`
	// Here you can find Delivery Time Code which was applied on your shipment
	DeliveryTimeCode string `json:"deliveryTimeCode,omitempty"`
	// Here you can find the product short name of your shipment
	ProductShortName   string                                                                 `json:"productShortName,omitempty"`
	ValueAddedServices []SupermodelIoLogisticsExpressCreateShipmentResponseValueAddedServices `json:"valueAddedServices,omitempty"`
	PickupDetails      *SupermodelIoLogisticsExpressCreateShipmentResponsePickupDetails       `json:"pickupDetails,omitempty"`
}
