/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

// Package defintion for rating related services
type SupermodelIoLogisticsExpressPackageRr struct {
	// Please contact your DHL Express representative if you wish to use a DHL specific package otherwise ignore this element.
	TypeCode string `json:"typeCode,omitempty"`
	// The weight of the package.
	Weight     float64      `json:"weight"`
	Dimensions *Dimensions1 `json:"dimensions"`
}
