/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

// RequestPickup schema definition
type SupermodelIoLogisticsExpressPickupRequest struct {
	// Identifies the date and time the package is ready for pickup Both the date and time portions of the string are expected to be used. The date should not be a past date or a date more than 10 days in the future. The time is the local time of the shipment based on the shipper's time zone. The date component must be in the format: YYYY-MM-DD; the time component must be in the format: HH:MM:SS using a 24 hour clock. The date and time parts are separated by the letter T (e.g. 2006-06-26T17:00:00 GMT+01:00).<BR>
	PlannedPickupDateAndTime string `json:"plannedPickupDateAndTime"`
	// The latest time the location premises is available to dispatch the DHL Express shipment. (HH:MM)
	CloseTime string `json:"closeTime,omitempty"`
	// Provides information on where the package should be picked up by DHL courier. <BR>
	Location string `json:"location,omitempty"`
	// Provides information on where the package should be picked up by DHL courier. <BR>
	LocationType string                                `json:"locationType,omitempty"`
	Accounts     []SupermodelIoLogisticsExpressAccount `json:"accounts"`
	// Details special pickup instructions you may wish to send to the DHL Courier.
	SpecialInstructions []SupermodelIoLogisticsExpressPickupRequestSpecialInstructions `json:"specialInstructions,omitempty"`
	// Please provide additional pickup remark
	Remark          string                                                    `json:"remark,omitempty"`
	CustomerDetails *SupermodelIoLogisticsExpressPickupRequestCustomerDetails `json:"customerDetails"`
	// Please provide details related to shipment you want to do the pickup for
	ShipmentDetails []SupermodelIoLogisticsExpressPickupRequestShipmentDetails `json:"shipmentDetails"`
}
