/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

type SupermodelIoLogisticsExpressCreateShipmentRequest struct {
	// Identifies the date and time the package is tendered. Both the date and time portions of the string are expected to be used. The date should not be a past date or a date more than 10 days in the future. The time is the local time of the shipment based on the shipper's time zone. The date component must be in the format: YYYY-MM-DD; the time component must be in the format: HH:MM:SS using a 24 hour clock. The date and time parts are separated by the letter T (e.g. 2006-06-26T17:00:00 GMT+01:00).
	PlannedShippingDateAndTime string  `json:"plannedShippingDateAndTime"`
	Pickup                     *Pickup `json:"pickup"`
	// Please enter DHL Express Global Product code
	ProductCode string `json:"productCode"`
	// Please enter DHL Express Local Product code. Important when shipping domestic products.
	LocalProductCode string `json:"localProductCode,omitempty"`
	// Please advise if you want to get rate estimates for given shipment
	GetRateEstimates bool `json:"getRateEstimates,omitempty"`
	// Please enter all the DHL Express accounts and types to be used for this shipment
	Accounts []SupermodelIoLogisticsExpressAccount `json:"accounts"`
	// This section communicates additional shipping services, such as Insurance (or Shipment Value Protection).
	ValueAddedServices    []SupermodelIoLogisticsExpressValueAddedServices                        `json:"valueAddedServices,omitempty"`
	OutputImageProperties *SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties `json:"outputImageProperties,omitempty"`
	// Here you can declare your customer references
	CustomerReferences []SupermodelIoLogisticsExpressReference `json:"customerReferences,omitempty"`
	// Identifiers section is on the shipment level where you can optionaly provide a DHL Express waybill number. This has to be enabled by your DHL Express IT contact.
	Identifiers      []SupermodelIoLogisticsExpressIdentifier                           `json:"identifiers,omitempty"`
	CustomerDetails  *SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetails  `json:"customerDetails"`
	Content          *SupermodelIoLogisticsExpressCreateShipmentRequestContent          `json:"content"`
	DocumentImages   *[]SupermodelIoLogisticsExpressDocumentImagesInner                 `json:"documentImages,omitempty"`
	OnDemandDelivery *SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery `json:"onDemandDelivery,omitempty"`
	// Determines whether to request the On Demand Delivery (ODD) link. When set to true it will provide an URL link for the specified Waybill Number, Shipper Account Number. The default value is false, no ODD link URL is provided in the response message.
	RequestOndemandDeliveryURL bool `json:"requestOndemandDeliveryURL,omitempty"`
	// This is to support sending email notification once the shipment is created. The email will contain the basic information on the shipper, recipient, waybill number, and shipment information
	ShipmentNotification []SupermodelIoLogisticsExpressCreateShipmentRequestShipmentNotification `json:"shipmentNotification,omitempty"`
	// Please provide any charges you have already paid for this shipment, like freight paid upfront. To allow using this section please contact your DHL Express representative
	PrepaidCharges []SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidCharges `json:"prepaidCharges,omitempty"`
	// If set to true, response will return transliterated text of shipper and receiver details.
	GetTransliteratedResponse bool                   `json:"getTransliteratedResponse,omitempty"`
	EstimatedDeliveryDate     *EstimatedDeliveryDate `json:"estimatedDeliveryDate,omitempty"`
	// Provides additional information in the response like service area details, routing code and pickup-related information
	GetAdditionalInformation []SupermodelIoLogisticsExpressCreateShipmentRequestGetAdditionalInformation `json:"getAdditionalInformation,omitempty"`
	ParentShipment           *SupermodelIoLogisticsExpressCreateShipmentRequestParentShipment            `json:"parentShipment,omitempty"`
}
