/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

// Here you can modify label, waybillDoc, invoice and receipt properties
type SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties struct {
	// Printer DPI Resolution for X-axis and Y-axis (in DPI) for transport label and waybill document output
	PrinterDPI float64 `json:"printerDPI,omitempty"`
	// Customer barcodes to be printed on supported transport label templates
	CustomerBarcodes []SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesCustomerBarcodes `json:"customerBarcodes,omitempty"`
	// Customer Logo Image to be printed on transport label
	CustomerLogos []SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesCustomerLogos `json:"customerLogos,omitempty"`
	// Please provide the format of the output documents. Note that invoice and receipt will always come back as PDF
	EncodingFormat string `json:"encodingFormat,omitempty"`
	// Here the image options are defined for label, waybillDoc, invoice, receipt and QRcode
	ImageOptions []SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions `json:"imageOptions,omitempty"`
	// When set to true it will generate a single PDF or thermal output file for the Transport Label, a single PDF or thermal output file for the Waybill document and a single PDF file consisting of Commercial Invoice and Shipment Receipt. The default value is false, a single PDF or thermal output image file consists of Transport Label and single PDF or thermal output image file for Waybill Document will be returned in create shipment response.
	SplitTransportAndWaybillDocLabels bool `json:"splitTransportAndWaybillDocLabels,omitempty"`
	// When set to true it will generate a single PDF or thermal output image file consists of Transport Label, Waybill Document, Shipment Receipt and Commercial Invoice.<BR>          The default value is false, where a single PDF or thermal output image file consists of Transport Label + Waybill Document and single PDF or thermal output image file for Shipment Receipt and Customs Invoice will be returned.
	AllDocumentsInOneImage bool `json:"allDocumentsInOneImage,omitempty"`
	// When set to true it will generate a single PDF or thermal output image file for each page for the Transport Label and single PDF or thermal output image file for Waybill Document will be returned in the create shipment response. The default value is false, a single PDF or thermal output image file for each page for Transport Label and single PDF or thermal output image file for Waybill Document will be returned in create shipment response.
	SplitDocumentsByPages bool `json:"splitDocumentsByPages,omitempty"`
	// When set to true it will generate a single PDF or thermal output image file consisting of Transport Label + Waybill Document, a single file consist of Commercial Invoice and a single file consist of Shipment Receipt. The default value is false, a single PDF or thermal output image file consists of Transport Label + Waybill Document and single PDF or thermal output image file for Shipment Receipt and Customs Invoice will be returned in create shipment response.
	SplitInvoiceAndReceipt bool `json:"splitInvoiceAndReceipt,omitempty"`
	// When set to true it will generate a single PDF file consisting of Transport Label, Waybill Document and Shipment Receipt. The default value is false, a single PDF or thermal output image file consists of Transport Label + Waybill Document and single PDF file for Shipment Receipt will be returned in create shipment response.  Applicable only when #/outputImageProperties/imageOptions/0/typeCode is 'receipt' and #/outputImageProperties/encodingFormat is PDF.
	ReceiptAndLabelsInOneImage bool `json:"receiptAndLabelsInOneImage,omitempty"`
}
