/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

// Package definition for /shipments
type SupermodelIoLogisticsExpressPackage struct {
	// Please contact your DHL Express representative if you wish to use a DHL specific package otherwise ignore this element.
	TypeCode string `json:"typeCode,omitempty"`
	// The weight of the package.
	Weight     float64     `json:"weight"`
	Dimensions *Dimensions `json:"dimensions"`
	// Here you can declare your customer references for each package
	CustomerReferences []SupermodelIoLogisticsExpressPackageReference `json:"customerReferences,omitempty"`
	// Identifiers section is on the package level where you can optionaly provide a DHL Express waybill number. This has to be enabled by your DHL Express IT contact.
	Identifiers []SupermodelIoLogisticsExpressIdentifier `json:"identifiers,omitempty"`
	// Please enter description of content for each package
	Description string `json:"description,omitempty"`
	// This allows you to define up to two bespoke barcodes on the DHL Express Tranport label. To use this feature please set outputImageProperties/imageOptions/templateName as ECOM26_84CI_003 for typeCode=label
	LabelBarcodes []SupermodelIoLogisticsExpressPackageLabelBarcodes `json:"labelBarcodes,omitempty"`
	// This allows you to enter up to two bespoke texts on the DHL Express Tranport label. To use this feature please set outputImageProperties/imageOptions/templateName as ECOM26_84CI_003 for typeCode=label
	LabelText []SupermodelIoLogisticsExpressPackageLabelText `json:"labelText,omitempty"`
	// Please enter additional customer description
	LabelDescription string `json:"labelDescription,omitempty"`
}
