/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

// MyDHL API REST /shipments response schema
type SupermodelIoLogisticsExpressCreateShipmentResponse struct {
	// URL where the request has been sent to
	Url string `json:"url,omitempty"`
	// Here you will receive Shipment Identification Number of your package
	ShipmentTrackingNumber string `json:"shipmentTrackingNumber,omitempty"`
	// If you requested pickup for your shipment you can use this URL to cancel the pickup
	CancelPickupUrl string `json:"cancelPickupUrl,omitempty"`
	// You can use ths URL to track your shipment
	TrackingUrl string `json:"trackingUrl,omitempty"`
	// If you asked for pickup service here you will find Dispach Confirmation Number which identifies your pickup booking
	DispatchConfirmationNumber string `json:"dispatchConfirmationNumber,omitempty"`
	// Here you can find information for all pieces your shipment is having like Piece Identification Number
	Packages []SupermodelIoLogisticsExpressCreateShipmentResponsePackages `json:"packages,omitempty"`
	// Here you can find all documents created for the shipment like Transport and WaybillDoc labels, Invoice, Receipt
	Documents []SupermodelIoLogisticsExpressCreateShipmentResponseDocuments1 `json:"documents,omitempty"`
	// In this field you will find the On Demand Delivery (ODD) URL link if requested
	OnDemandDeliveryURL string `json:"onDemandDeliveryURL,omitempty"`
	// Here you can find additional information related to your shipment when you ask for it in the request
	ShipmentDetails []SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetails `json:"shipmentDetails,omitempty"`
	// Here you can find rates related to your shipment
	ShipmentCharges       []SupermodelIoLogisticsExpressCreateShipmentResponseShipmentCharges      `json:"shipmentCharges,omitempty"`
	BarcodeInfo           *SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo           `json:"barcodeInfo,omitempty"`
	EstimatedDeliveryDate *SupermodelIoLogisticsExpressCreateShipmentResponseEstimatedDeliveryDate `json:"estimatedDeliveryDate,omitempty"`
	Warnings              []string                                                                 `json:"warnings,omitempty"`
}
