/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

type SupermodelIoLogisticsExpressAddressCreateShipmentRequest struct {
	// Please enter your postcode or leave empty if the address doesn't have a postcode
	PostalCode string `json:"postalCode"`
	// Please enter the city
	CityName string `json:"cityName"`
	// Please enter ISO country code
	CountryCode string `json:"countryCode"`
	// Please enter your province or state code
	ProvinceCode string `json:"provinceCode,omitempty"`
	// Please enter address line 1
	AddressLine1 string `json:"addressLine1"`
	// Please enter address line 2
	AddressLine2 string `json:"addressLine2,omitempty"`
	// Please enter address line 3
	AddressLine3 string `json:"addressLine3,omitempty"`
	// Please enter your suburb or county name
	CountyName string `json:"countyName,omitempty"`
	// Please enter your state or province name
	ProvinceName string `json:"provinceName,omitempty"`
	// Please enter your country name
	CountryName string `json:"countryName,omitempty"`
}
