/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

type SupermodelIoLogisticsExpressRatesDeliveryCapabilities struct {
	// Delivery Date capabilities considering customs clearance days.<BR>                QDDF: is the fastest (\"docs\") transit time as quoted to the customer at booking or shipment creation. No custom clearance is considered.<BR>                QDDC: constitutes DHL's service commitment as quoted at booking/shipment creation. QDDc builds in clearance time, and potentially other special operational non-transport component(s), when relevant.
	DeliveryTypeCode string `json:"deliveryTypeCode,omitempty"`
	// This is the estimated date/time the shipment will be delivered by for the rated shipment and product listed
	EstimatedDeliveryDateAndTime string `json:"estimatedDeliveryDateAndTime,omitempty"`
	// The DHL Service Area Code for the destination of the Shipment
	DestinationServiceAreaCode string `json:"destinationServiceAreaCode,omitempty"`
	// The DHL Facility Code for the Destination
	DestinationFacilityAreaCode string `json:"destinationFacilityAreaCode,omitempty"`
	// This is additional transit delays (in days) for shipment delivered to the<BR>                mentioned city or postal area following arrival at the service area.
	DeliveryAdditionalDays float64 `json:"deliveryAdditionalDays,omitempty"`
	// Destination day of the week number
	DeliveryDayOfWeek float64 `json:"deliveryDayOfWeek,omitempty"`
	// The number of transit days
	TotalTransitDays float64 `json:"totalTransitDays,omitempty"`
}
