/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

// Here you can find barcode details in base64
type SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo struct {
	// Barcode base64 encoded airwaybill number
	ShipmentIdentificationNumberBarcodeContent string `json:"shipmentIdentificationNumberBarcodeContent,omitempty"`
	// Barcode base64 image of origin service area code, destination service area code and global product code
	OriginDestinationServiceTypeBarcodeContent string `json:"originDestinationServiceTypeBarcodeContent,omitempty"`
	// Barcode base64 image of DHL routing code
	RoutingBarcodeContent string `json:"routingBarcodeContent,omitempty"`
	// Here you can find barcode details for each piece
	TrackingNumberBarcodes []SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfoTrackingNumberBarcodes `json:"trackingNumberBarcodes,omitempty"`
}
