/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

type SupermodelIoLogisticsExpressTrackingResponsePieces struct {
	Number                 float64 `json:"number,omitempty"`
	TypeCode               string  `json:"typeCode,omitempty"`
	ShipmentTrackingNumber string  `json:"shipmentTrackingNumber,omitempty"`
	TrackingNumber         string  `json:"trackingNumber,omitempty"`
	Description            string  `json:"description,omitempty"`
	// The weight of the package.
	Weight float64 `json:"weight,omitempty"`
	// The weight of the package.
	DimensionalWeight float64 `json:"dimensionalWeight,omitempty"`
	// The weight of the package.
	ActualWeight       float64                                               `json:"actualWeight,omitempty"`
	Dimensions         *Dimensions2                                          `json:"dimensions,omitempty"`
	ActualDimensions   *Dimensions3                                          `json:"actualDimensions,omitempty"`
	UnitOfMeasurements string                                                `json:"unitOfMeasurements,omitempty"`
	ShipperReferences  []SupermodelIoLogisticsExpressReference               `json:"shipperReferences,omitempty"`
	Events             []SupermodelIoLogisticsExpressTrackingResponseEvents1 `json:"events"`
}
