/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

type SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidCharges struct {
	// Please enter type of prepaid charge. At this moment only freight is supported
	TypeCode string `json:"typeCode"`
	// Please enter currency for the value you have entered into value field
	Currency string `json:"currency"`
	// Please enter nominal value related to the charge
	Value float64 `json:"value"`
	// Please enter method you have used to pay the charges. At this moment only cash is supported
	Method string `json:"method"`
}
