/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

type SupermodelIoLogisticsExpressRatesBreakdown1 struct {
	// Name of the charge
	Name string `json:"name,omitempty"`
	// Special service or extra charge code. This is the code you would have to use in the /shipment service if you wish to add an optional Service such as Saturday delivery
	ServiceCode string `json:"serviceCode,omitempty"`
	// Local service code
	LocalServiceCode string `json:"localServiceCode,omitempty"`
	// Charge type or category.<BR>                        Possible values;<BR>                        - DUTY<BR>                        - TAX<BR>                        - FEE
	TypeCode string `json:"typeCode"`
	// Special service charge code type for service. XCH type charge codes are Optional Services and should be displayed to users for selection.<BR>                        The possible values are;<BR>                        - XCH = Extra charge<BR>                        - FEE = Fee<BR>                        - SCH = Surcharge<BR>                        - NRI = Non Revenue Item<BR>                        Other charges may be automatically returned when applicable.
	ServiceTypeCode string `json:"serviceTypeCode,omitempty"`
	// The charge amount of the line item charge.
	Price float64 `json:"price"`
	// This the currency of the rated shipment for the prices listed.
	PriceCurrency string `json:"priceCurrency,omitempty"`
	// Customer agreement indicator for product and services, if service is offered with prior customer agreement
	IsCustomerAgreement bool `json:"isCustomerAgreement,omitempty"`
	// Indicator if the special service is marketed service
	IsMarketedService bool `json:"isMarketedService,omitempty"`
	// Indicator if there is any discount allowed
	IsBillingServiceIndicator bool                                               `json:"isBillingServiceIndicator,omitempty"`
	PriceBreakdown            []SupermodelIoLogisticsExpressRatesPriceBreakdown2 `json:"priceBreakdown,omitempty"`
	// Tariff Rate Formula on Line Item Level
	TariffRateFormula string `json:"tariffRateFormula,omitempty"`
}
