/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

// Here you can provide data in case you wish to use DHL Express On demand delivery service
type SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery struct {
	// Please choose from one of the delivery options
	DeliveryOption string `json:"deliveryOption"`
	// If delivery option is signatureDelivery please specify location where to leave the shipment
	Location string `json:"location,omitempty"`
	// Please enter additional information that might be useful for the DHL Express courier
	SpecialInstructions string `json:"specialInstructions,omitempty"`
	// Please provide entry code to gain access to an apartment complex or gate
	GateCode string `json:"gateCode,omitempty"`
	// In ase your deliveryOption is 'neighbour' please specify where to leave the package
	WhereToLeave string `json:"whereToLeave,omitempty"`
	// In case you wish to leave the package with neighbour please provide the neighbour's name
	NeighbourName string `json:"neighbourName,omitempty"`
	// In case you wish to leave the package with neighbour please provide the neighbour's house number
	NeighbourHouseNumber string `json:"neighbourHouseNumber,omitempty"`
	// In case your delivery option is 'signatureRelease' please provide name of the person who is authorized to sign and receive the package
	AuthorizerName string `json:"authorizerName,omitempty"`
	// In case your delivery option is 'servicepoint' please provide unique DHL Express Service point location ID of where the parcel should be delieverd (please contact your local DHL Express Account Manager to obtain the list of the servicepoint IDs)
	ServicePointId string `json:"servicePointId,omitempty"`
	// for future use
	RequestedDeliveryDate string `json:"requestedDeliveryDate,omitempty"`
}
