/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

type SupermodelIoLogisticsExpressPickupRequestShipmentDetails struct {
	// Please provide DHL Express Global product code of the shipment
	ProductCode string `json:"productCode"`
	// Please provide DHL Express Local product code of the shipment
	LocalProductCode string `json:"localProductCode,omitempty"`
	// Please enter all the DHL Express accounts related to this shipment
	Accounts []SupermodelIoLogisticsExpressAccount `json:"accounts,omitempty"`
	// This section communicates additional shipping services, such as Insurance (or Shipment Value Protection).
	ValueAddedServices []SupermodelIoLogisticsExpressValueAddedServicesRates `json:"valueAddedServices,omitempty"`
	// For customs purposes please advise if your shipment is dutiable (true) or non dutiable (false)
	IsCustomsDeclarable bool `json:"isCustomsDeclarable"`
	// For customs purposes please advise on declared value of the shipment
	DeclaredValue float64 `json:"declaredValue,omitempty"`
	// For customs purposes please advise on declared value currency code of the shipment
	DeclaredValueCurrency string `json:"declaredValueCurrency,omitempty"`
	// Please enter Unit of measurement - metric,imperial
	UnitOfMeasurement string `json:"unitOfMeasurement"`
	// Please provide Shipment Identification number (AWB number)
	ShipmentTrackingNumber string `json:"shipmentTrackingNumber,omitempty"`
	// Here you can define properties per package
	Packages []SupermodelIoLogisticsExpressPackageRr `json:"packages"`
}
