/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

// Here you can find pickup details
type SupermodelIoLogisticsExpressCreateShipmentResponsePickupDetails struct {
	// Pickup booking cutoff time
	LocalCutoffDateAndTime string `json:"localCutoffDateAndTime,omitempty"`
	// Pickup cutoff time in GMT
	GmtCutoffTime string `json:"gmtCutoffTime,omitempty"`
	// Pickup booking cutoff time in GMT offset
	CutoffTimeOffset string `json:"cutoffTimeOffset,omitempty"`
	// The DHL earliest time possible for pickup
	PickupEarliest string `json:"pickupEarliest,omitempty"`
	// The DHL latest time possible for pickup
	PickupLatest string `json:"pickupLatest,omitempty"`
	// The number of transit days
	TotalTransitDays string `json:"totalTransitDays,omitempty"`
	// This is additional transit delays (in days) for shipment picked up from the mentioned city or postal area to arrival at the service area
	PickupAdditionalDays string `json:"pickupAdditionalDays,omitempty"`
	// This is additional transit delays (in days) for shipment delivered to the mentioned city or postal area following arrival at the service area
	DeliveryAdditionalDays string `json:"deliveryAdditionalDays,omitempty"`
	// Pickup day of the week number
	PickupDayOfWeek string `json:"pickupDayOfWeek,omitempty"`
	// Destination day of the week number
	DeliveryDayOfWeek string `json:"deliveryDayOfWeek,omitempty"`
}
