/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

type SupermodelIoLogisticsExpressProductsBreakdown struct {
	// Breakdown Name
	Name string `json:"name,omitempty"`
	// Special service or extra charge code.  This is the code you would have to use in the /shipment service if you wish to add an optional Service such as Saturday delivery
	ServiceCode string `json:"serviceCode,omitempty"`
	// Local service code
	LocalServiceCode string `json:"localServiceCode,omitempty"`
	// Breakdown type code
	TypeCode string `json:"typeCode,omitempty"`
	// Special service charge code type for service.
	ServiceTypeCode string `json:"serviceTypeCode,omitempty"`
	// Customer agreement indicator for product and services, if service is offered with prior customer agreement
	IsCustomerAgreement bool `json:"isCustomerAgreement,omitempty"`
	// Indicator if the special service is marketed service
	IsMarketedService bool `json:"isMarketedService,omitempty"`
	// Indicator if there is any discount allowed
	IsBillingServiceIndicator bool `json:"isBillingServiceIndicator,omitempty"`
}
