/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

type SupermodelIoLogisticsExpressRatesPickupCapabilities struct {
	// This indicator has values of Y or N, and tells the consumer if the service in the response has a pickup date on the same day as the requested shipment date (per the request).
	NextBusinessDay bool `json:"nextBusinessDay,omitempty"`
	// This is the cutoff time for the service<BR>                offered in the response. This represents the latest time (local to origin) which the shipment can be tendered to the courier for that service on that day.
	LocalCutoffDateAndTime string `json:"localCutoffDateAndTime,omitempty"`
	// Pickup cut off time in GMT
	GMTCutoffTime string `json:"GMTCutoffTime,omitempty"`
	// The DHL earliest time possible for pickup
	PickupEarliest string `json:"pickupEarliest,omitempty"`
	// The DHL latest time possible for pickup
	PickupLatest string `json:"pickupLatest,omitempty"`
	// The DHL Service Area Code for the origin of the Shipment
	OriginServiceAreaCode string `json:"originServiceAreaCode,omitempty"`
	// The DHL Facility Code for the Origin
	OriginFacilityAreaCode string `json:"originFacilityAreaCode,omitempty"`
	// This is additional transit delays (in days) for shipment picked up from the mentioned city or postal area to arrival at the service area.
	PickupAdditionalDays float64 `json:"pickupAdditionalDays,omitempty"`
	// Pickup day of the week number
	PickupDayOfWeek float64 `json:"pickupDayOfWeek,omitempty"`
}
