/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

// Please provide invoice related information
type SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationInvoice struct {
	// Please enter commercial invoice number
	Number string `json:"number"`
	// Please enter commercial invoice date
	Date string `json:"date"`
	// Please enter who has signed the invoce
	SignatureName string `json:"signatureName,omitempty"`
	// Please provide title of person who has signed the invoice
	SignatureTitle string `json:"signatureTitle,omitempty"`
	// Please provide the signature image
	SignatureImage string `json:"signatureImage,omitempty"`
	// Shipment instructions for customs invoice printing purposes. Printed only when using Customs Invoice template COMMERCIAL_INVOICE_04. If using Customs Invoice template    COMMERCIAL_INVOICE_04, recommended max length is 120 characters.
	Instructions []string `json:"instructions,omitempty"`
	// Customer data text to be printed in<BR>                  customs invoice.<BR>                  Printed only when using Customs<BR>                  Invoice template<BR>                  COMMERCIAL_INVOICE_04.
	CustomerDataTextEntries []string `json:"customerDataTextEntries,omitempty"`
	// Please provide the total net weight
	TotalNetWeight float64 `json:"totalNetWeight,omitempty"`
	// Please provide the total gross weight
	TotalGrossWeight float64 `json:"totalGrossWeight,omitempty"`
	// Please provide the customer references at invoice level
	CustomerReferences []SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationInvoiceCustomerReferences `json:"customerReferences,omitempty"`
	// Please provide the terms of payment
	TermsOfPayment          string                                                                                                   `json:"termsOfPayment,omitempty"`
	IndicativeCustomsValues *SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationInvoiceIndicativeCustomsValues `json:"indicativeCustomsValues,omitempty"`
}
