/*
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * API version: 2.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dhlapi

type SupermodelIoLogisticsExpressExportDeclarationLineItems struct {
	// Please provide line item number
	Number int32 `json:"number"`
	// Please provide description of the line item
	Description string `json:"description"`
	// Please provide monetary value of the line item
	Price    float64                                                `json:"price"`
	Quantity *SupermodelIoLogisticsExpressExportDeclarationQuantity `json:"quantity"`
	// Please provide Commodity codes for the shipment at item line level
	CommodityCodes []SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationCommodityCodes `json:"commodityCodes,omitempty"`
	// Please provide the reason for export
	ExportReasonType string `json:"exportReasonType,omitempty"`
	// Please enter two letter ISO manufacturer country code
	ManufacturerCountry string                                               `json:"manufacturerCountry"`
	Weight              *SupermodelIoLogisticsExpressExportDeclarationWeight `json:"weight"`
	// Please provide if the Taxes is paid for the line item
	IsTaxesPaid bool `json:"isTaxesPaid,omitempty"`
	// Please provide the Customer References for the line item
	CustomerReferences []SupermodelIoLogisticsExpressExportDeclarationCustomerReferences `json:"customerReferences,omitempty"`
	// Please provide the customs documents details
	CustomsDocuments []SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationCustomsDocuments `json:"customsDocuments,omitempty"`
}
